version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dream-tracker-sam"
s3_bucket = ""
s3_prefix = "dream-tracker-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = ""
image_repositories = []